baseURL = "http://example.org/"
languageCode = "en-us"
title = "Agnes Site"
theme = "Agnes"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "Ported to Hugo by Debashish"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
[params.social]
	TwitterURL = "https://twitter.com/podbharati"
	GoogleURL = "http://google.com"
	FacebookURL = "https://facebook.com/podbharati"
		
[params.content]
	LeadTitle = "Maria Frutuoso"
	LeadDescription = "Consultoria especializada"
	SubDescription = "Cuidados com a saúde e bem estar, oferecendo planos que atendem sua necessidade!"
	
	ButtonCaption = "Fale conosco"
	ButtonURL = "https://api.whatsapp.com/send?phone=92991852037"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Odontológico"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Individual"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Empresarial"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Familiar"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Starter"
	PricingRate = "27"	
	ButtonCaption = "Get Early Access"
 	ButtonURL = "https://example.com/early-access.html"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	

[[params.pricing]]
	PricingTitle = "Professional"
	PricingRate = "97"
	ButtonCaption = "Get Earlier Access"
 	ButtonURL = "https://example.com/earlier-access.html"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"		
	
# [[params.pricing]]
#	PricingTitle = "Business"
#	PricingRate = "147"
#	ButtonCaption = "Get Earliest Access"
 #	ButtonURL = "https://example.com/earliest-access.html"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text" 

[caches]
  [caches.images]
    dir = ':cacheDir/images'